#!/bin/bash

set -eo pipefail

if [[ $# -lt 1 ]]; then
  echo "Usage: $0 <instance name> [<input file>]"
  exit 1
fi

INSTANCE_NAME="$1"
INPUT_FILE="$2"

INPUT_FILE="$INPUT_FILE" node index.js remote.json "$INSTANCE_NAME"
